import asyncio
import logging
from typing import Dict, List, Any, Optional
from datetime import datetime
from sqlalchemy.orm import Session
from app.models.soar import (
    SOARPlaybook, SOARAction, SOARExecutionLog, 
    ActionType, ExecutionStatus, TriggerType
)
from app.models.alert import Alert
from app.models.incident import Incident
from app.services.redis_client import redis_client, REDIS_CHANNELS
from app.core.config import settings
import uuid
import json
import httpx
import subprocess
import smtplib
from email.mime.text import MimeText
from email.mime.multipart import MimeMultipart

logger = logging.getLogger(__name__)

class SOARActionExecutor:
    """Base class for SOAR action executors"""
    
    async def execute(self, action: SOARAction, context: Dict[str, Any]) -> Dict[str, Any]:
        """Execute the action"""
        raise NotImplementedError

class BlockIPAction(SOARActionExecutor):
    """Block IP address action"""
    
    async def execute(self, action: SOARAction, context: Dict[str, Any]) -> Dict[str, Any]:
        try:
            ip_address = context.get("source_ip")
            if not ip_address:
                return {"status": "failed", "error": "No IP address provided"}
            
            # Execute firewall command (example)
            config = action.config or {}
            firewall_command = config.get("command", f"iptables -A INPUT -s {ip_address} -j DROP")
            
            result = subprocess.run(
                firewall_command.split(),
                capture_output=True,
                text=True,
                timeout=30
            )
            
            if result.returncode == 0:
                return {
                    "status": "success",
                    "message": f"Successfully blocked IP {ip_address}",
                    "command": firewall_command
                }
            else:
                return {
                    "status": "failed",
                    "error": result.stderr,
                    "command": firewall_command
                }
        
        except subprocess.TimeoutExpired:
            return {"status": "failed", "error": "Command timeout"}
        except Exception as e:
            return {"status": "failed", "error": str(e)}

class NotifyAction(SOARActionExecutor):
    """Send notification action"""
    
    async def execute(self, action: SOARAction, context: Dict[str, Any]) -> Dict[str, Any]:
        try:
            config = action.config or {}
            notification_type = config.get("type", "email")
            
            if notification_type == "email":
                return await self._send_email_notification(action, context)
            elif notification_type == "slack":
                return await self._send_slack_notification(action, context)
            elif notification_type == "webhook":
                return await self._send_webhook_notification(action, context)
            else:
                return {"status": "failed", "error": f"Unknown notification type: {notification_type}"}
        
        except Exception as e:
            return {"status": "failed", "error": str(e)}
    
    async def _send_email_notification(self, action: SOARAction, context: Dict[str, Any]) -> Dict[str, Any]:
        config = action.config or {}
        
        # Create email
        msg = MimeMultipart()
        msg['From'] = config.get("from_email", "security@sentinelx.com")
        msg['To'] = config.get("to_email", "admin@sentinelx.com")
        msg['Subject'] = f"Security Alert: {context.get('title', 'SOAR Alert')}"
        
        # Email body
        body = f"""
        Security Alert Details:
        
        Title: {context.get('title', 'N/A')}
        Description: {context.get('description', 'N/A')}
        Severity: {context.get('severity', 'N/A')}
        Source IP: {context.get('source_ip', 'N/A')}
        Timestamp: {context.get('timestamp', 'N/A')}
        
        This alert was automatically generated by SentinelX SOAR engine.
        """
        
        msg.attach(MimeText(body, 'plain'))
        
        # Send email (example using SMTP)
        smtp_config = config.get("smtp", {})
        server = smtplib.SMTP(smtp_config.get("host", "localhost"), smtp_config.get("port", 587))
        server.starttls()
        server.login(smtp_config.get("username"), smtp_config.get("password"))
        
        text = msg.as_string()
        server.sendmail(msg['From'], msg['To'], text)
        server.quit()
        
        return {
            "status": "success",
            "message": "Email notification sent successfully",
            "recipient": msg['To']
        }
    
    async def _send_slack_notification(self, action: SOARAction, context: Dict[str, Any]) -> Dict[str, Any]:
        config = action.config or {}
        webhook_url = config.get("webhook_url")
        
        if not webhook_url:
            return {"status": "failed", "error": "Slack webhook URL not configured"}
        
        # Create Slack message
        slack_message = {
            "text": f"🚨 Security Alert: {context.get('title', 'SOAR Alert')}",
            "attachments": [
                {
                    "color": self._get_slack_color(context.get('severity')),
                    "fields": [
                        {"title": "Description", "value": context.get('description', 'N/A'), "short": False},
                        {"title": "Severity", "value": context.get('severity', 'N/A'), "short": True},
                        {"title": "Source IP", "value": context.get('source_ip', 'N/A'), "short": True},
                        {"title": "Timestamp", "value": context.get('timestamp', 'N/A'), "short": True}
                    ]
                }
            ]
        }
        
        # Send to Slack
        async with httpx.AsyncClient() as client:
            response = await client.post(webhook_url, json=slack_message, timeout=30)
            
            if response.status_code == 200:
                return {
                    "status": "success",
                    "message": "Slack notification sent successfully"
                }
            else:
                return {
                    "status": "failed",
                    "error": f"Slack API error: {response.status_code} - {response.text}"
                }
    
    async def _send_webhook_notification(self, action: SOARAction, context: Dict[str, Any]) -> Dict[str, Any]:
        config = action.config or {}
        webhook_url = config.get("url")
        
        if not webhook_url:
            return {"status": "failed", "error": "Webhook URL not configured"}
        
        # Create webhook payload
        payload = {
            "alert": context,
            "timestamp": datetime.utcnow().isoformat(),
            "source": "sentinelx-soar"
        }
        
        # Send webhook
        async with httpx.AsyncClient() as client:
            response = await client.post(
                webhook_url, 
                json=payload, 
                timeout=30,
                headers=config.get("headers", {})
            )
            
            if response.status_code in [200, 201, 202]:
                return {
                    "status": "success",
                    "message": "Webhook notification sent successfully",
                    "response_code": response.status_code
                }
            else:
                return {
                    "status": "failed",
                    "error": f"Webhook error: {response.status_code} - {response.text}"
                }
    
    def _get_slack_color(self, severity: str) -> str:
        """Get Slack color based on severity"""
        colors = {
            "critical": "danger",
            "high": "warning",
            "medium": "warning",
            "low": "good"
        }
        return colors.get(severity.lower(), "warning")

class DisableUserAction(SOARActionExecutor):
    """Disable user account action"""
    
    async def execute(self, action: SOARAction, context: Dict[str, Any]) -> Dict[str, Any]:
        try:
            user_id = context.get("user_id")
            if not user_id:
                return {"status": "failed", "error": "No user ID provided"}
            
            # This would integrate with your user management system
            # For now, we'll just log the action
            logger.info(f"Disabling user {user_id} due to security alert")
            
            return {
                "status": "success",
                "message": f"User {user_id} disabled successfully"
            }
        
        except Exception as e:
            return {"status": "failed", "error": str(e)}

class SOAREngine:
    """Main SOAR engine"""
    
    def __init__(self):
        self.is_running = False
        self.action_executors = {
            ActionType.BLOCK_IP: BlockIPAction(),
            ActionType.NOTIFY: NotifyAction(),
            ActionType.DISABLE_USER: DisableUserAction(),
        }
        self.running_executions = {}
        self.max_concurrent = settings.SOAR_MAX_CONCURRENT_EXECUTIONS
    
    async def start(self):
        """Start the SOAR engine"""
        if self.is_running:
            logger.warning("SOAR engine is already running")
            return
        
        self.is_running = True
        logger.info("SOAR engine started")
        
        # Start background processing
        asyncio.create_task(self._process_triggers_loop())
    
    async def stop(self):
        """Stop the SOAR engine"""
        self.is_running = False
        logger.info("SOAR engine stopped")
    
    async def execute_playbook(self, db: Session, playbook_id: uuid.UUID, 
                           context: Dict[str, Any], triggered_by: Optional[uuid.UUID] = None) -> SOARExecutionLog:
        """Execute a SOAR playbook"""
        
        # Check concurrent execution limit
        if len(self.running_executions) >= self.max_concurrent:
            raise Exception(f"Maximum concurrent executions ({self.max_concurrent}) reached")
        
        # Get playbook
        playbook = db.query(SOARPlaybook).filter(
            SOARPlaybook.id == playbook_id,
            SOARPlaybook.is_active == True
        ).first()
        
        if not playbook:
            raise Exception(f"Playbook {playbook_id} not found or inactive")
        
        # Create execution log
        execution = SOARExecutionLog(
            playbook_id=playbook_id,
            alert_id=context.get("alert_id"),
            incident_id=context.get("incident_id"),
            status=ExecutionStatus.RUNNING,
            triggered_by=triggered_by,
            started_at=datetime.utcnow()
        )
        
        db.add(execution)
        db.commit()
        db.refresh(execution)
        
        # Add to running executions
        self.running_executions[execution.id] = execution
        
        try:
            # Get actions ordered by order_index
            actions = db.query(SOARAction).filter(
                SOARAction.playbook_id == playbook_id,
                SOARAction.is_active == True
            ).order_by(SOARAction.order_index).all()
            
            execution_results = []
            
            for action in actions:
                # Get action executor
                executor = self.action_executors.get(action.action_type)
                if not executor:
                    logger.warning(f"No executor found for action type: {action.action_type}")
                    continue
                
                try:
                    # Execute action with timeout
                    result = await asyncio.wait_for(
                        executor.execute(action, context),
                        timeout=action.timeout_seconds
                    )
                    
                    execution_results.append({
                        "action_id": str(action.id),
                        "action_type": action.action_type,
                        "result": result
                    })
                    
                    # Check if action failed and should stop execution
                    if result.get("status") == "failed":
                        logger.error(f"Action {action.name} failed: {result.get('error')}")
                        break
                
                except asyncio.TimeoutError:
                    logger.error(f"Action {action.name} timed out")
                    execution_results.append({
                        "action_id": str(action.id),
                        "action_type": action.action_type,
                        "result": {"status": "failed", "error": "Action timeout"}
                    })
                    break
                
                except Exception as e:
                    logger.error(f"Error executing action {action.name}: {e}")
                    execution_results.append({
                        "action_id": str(action.id),
                        "action_type": action.action_type,
                        "result": {"status": "failed", "error": str(e)}
                    })
                    break
            
            # Update execution log
            execution.status = ExecutionStatus.SUCCESS
            execution.completed_at = datetime.utcnow()
            execution.execution_details = execution_results
            db.commit()
            
            # Publish execution result
            await redis_client.publish(REDIS_CHANNELS["SOAR"], {
                "execution_id": str(execution.id),
                "playbook_id": str(playbook_id),
                "status": execution.status,
                "results": execution_results
            })
            
            logger.info(f"Playbook {playbook.name} executed successfully")
            
        except Exception as e:
            # Update execution log with error
            execution.status = ExecutionStatus.FAILED
            execution.completed_at = datetime.utcnow()
            execution.error_message = str(e)
            db.commit()
            
            logger.error(f"Playbook {playbook.name} execution failed: {e}")
        
        finally:
            # Remove from running executions
            if execution.id in self.running_executions:
                del self.running_executions[execution.id]
        
        return execution
    
    async def _process_triggers_loop(self):
        """Background loop to process triggers"""
        while self.is_running:
            try:
                # Subscribe to alerts channel
                pubsub = await redis_client.subscribe(REDIS_CHANNELS["ALERTS"])
                
                async for message in pubsub.listen():
                    if message["type"] == "message":
                        try:
                            alert_data = json.loads(message["data"])
                            await self._check_alert_triggers(alert_data)
                        except Exception as e:
                            logger.error(f"Error processing alert trigger: {e}")
                
            except Exception as e:
                logger.error(f"Error in SOAR trigger loop: {e}")
                await asyncio.sleep(5)  # Wait before retrying
    
    async def _check_alert_triggers(self, alert_data: Dict[str, Any]):
        """Check if alert triggers any playbooks"""
        from app.models.database import SessionLocal
        db = SessionLocal()
        
        try:
            # Get playbooks that trigger on alerts
            playbooks = db.query(SOARPlaybook).filter(
                SOARPlaybook.trigger_type == TriggerType.ALERT,
                SOARPlaybook.is_active == True
            ).all()
            
            for playbook in playbooks:
                if await self._evaluate_trigger_conditions(playbook.trigger_conditions, alert_data):
                    # Execute playbook
                    context = {
                        "alert_id": alert_data.get("id"),
                        "severity": alert_data.get("severity"),
                        "title": alert_data.get("title"),
                        "description": alert_data.get("description"),
                        "source_ip": alert_data.get("source_ip")
                    }
                    
                    logger.info(f"Triggering playbook {playbook.name} for alert {alert_data.get('id')}")
                    await self.execute_playbook(db, playbook.id, context)
        
        finally:
            db.close()
    
    async def _evaluate_trigger_conditions(self, conditions: Dict[str, Any], alert_data: Dict[str, Any]) -> bool:
        """Evaluate if trigger conditions match alert data"""
        if not conditions:
            return True
        
        # Example condition evaluation
        severity_match = True
        if "severity" in conditions:
            required_severities = conditions["severity"]
            alert_severity = alert_data.get("severity")
            severity_match = alert_severity in required_severities
        
        # Add more condition types as needed
        return severity_match

# Global SOAR engine instance
soar_engine = SOAREngine()
